version:         '3.8'

services:

  app:
#    image:       simple-nodejs-app
    build:
      context:   .
    environment:
      HTTP_PORT: 3000
      NODE_ENV:  docker
    ports:
      - 3000:3000

#  test:
#    image:                   simple-nodejs-app-test:latest
#    command:                 ["sleep", "3600"]
#    environment:
#      APP_BASE_URL:          http://app:3000
#      APP_ASSEMBLY_VERSION:  0.4.1.22
