name: Build base image

on:
  workflow_dispatch:
  schedule:
    - cron:  '5 6 * * 0'
env:
  IMAGE_REPO: ghcr.io/aaheiev/base/nodejs
jobs:

  build:
    name: Build base image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to github container registry
      id: docker_login
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build docker image
      id: docker_app_build
      run: |
        docker_tag_exists=$(docker manifest inspect ${{ env.APP_IMAGE_REPO }}:$GITHUB_SHA > /dev/null ; echo $?)
        if [[ $docker_tag_exists == 0 ]]; then
          echo "Using existing image"
          docker pull ${{ env.IMAGE_REPO }}:$GITHUB_SHA
        else
          echo "Building new image"
          docker build -t ${{ env.IMAGE_REPO }}:$GITHUB_SHA ./base-docker-image
          docker push ${{ env.IMAGE_REPO }}:$GITHUB_SHA
        fi

    - name: Publish docker image tags
      run: |
        dateTag=$(date +%F)
        docker tag ${{ env.IMAGE_REPO }}:$GITHUB_SHA ${{ env.IMAGE_REPO }}:latest
        docker push ${{ env.IMAGE_REPO }}:latest
        docker tag ${{ env.IMAGE_REPO }}:$GITHUB_SHA ${{ env.IMAGE_REPO }}:$dateTag
        docker push ${{ env.IMAGE_REPO }}:$dateTag
