name: Build base image

on:
  push:
    branches:
      - main
      - build-base-image

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: |
        tag=$(date +%F)
        echo $tag
